# Generated by Django 5.0.1 on 2024-02-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.IntegerField(db_index=True, help_text='Первые 3 цифры номера телефона')),
                ('start_range', models.IntegerField(db_index=True, help_text='Начало диапазона номеров')),
                ('end_range', models.IntegerField(db_index=True, help_text='Конец диапазона номеров')),
                ('operator', models.CharField(help_text='Оператор номеров', max_length=255)),
                ('region', models.CharField(help_text='Регион номеров', max_length=255)),
                ('inn', models.IntegerField(help_text='ИНН оператора')),
            ],
        ),
    ]
