# Generated by Django 5.0.1 on 2024-02-04 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название оператора', max_length=255)),
                ('inn', models.IntegerField(help_text='ИНН оператора')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название региона', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='phonegroup',
            name='inn',
        ),
        migrations.AlterField(
            model_name='phonegroup',
            name='operator',
            field=models.ForeignKey(help_text='Оператор номеров', on_delete=django.db.models.deletion.CASCADE, to='checker_base.operator'),
        ),
        migrations.AlterField(
            model_name='phonegroup',
            name='region',
            field=models.ForeignKey(help_text='Регион номеров', on_delete=django.db.models.deletion.CASCADE, to='checker_base.region'),
        ),
    ]
