# Generated by Django 5.0.1 on 2024-02-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker_base', '0002_operator_region_remove_phonegroup_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='inn',
            field=models.CharField(help_text='ИНН оператора'),
        ),
    ]
