# Generated by Django 5.0.1 on 2024-02-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker_base', '0003_alter_operator_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='name',
            field=models.CharField(help_text='Название оператора', max_length=511),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(help_text='Название региона', max_length=511),
        ),
    ]
